In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Ai/Data Analysis /Dataset/Riyadh_Hotels.xlsx")
df.head(10)

,hotel_id,hotel_name,SOURCE,price,base_price,checkIn,checkOut,count,rating,Info,latitude,longitude
0,15215188,Fairmont Riyadh,all.accor.com,1605.00,NaN,2025-01-02,2025-01-03,220,4.5,NaN,24.808397,46.718050
1,9702375,Rosh Rayhaan by Rotana,Official Site,813.75,693.75,2025-01-02,2025-01-03,1311,4.5,"['Free breakfast available', 'Free cancellation']",24.700346,46.682137
2,15756839,Hilton Riyadh Hotel & Residences,Booking.com,1128.75,1128.75,2025-01-02,2025-01-03,1626,4.5,NaN,24.785522,46.727880
3,24143026,Joudyan Hotel,MakeMyTrip,588.75,472.50,2025-01-02,2025-01-03,317,5.0,"['Free breakfast available', 'Free cancellation']",24.713552,46.675297
4,969150,"Holiday Inn Riyadh - al Qasr, an IHG hotel",Booking.com,633.75,633.75,2025-01-02,2025-01-03,1073,4.5,NaN,24.683914,46.688030
5,7789088,"Crowne Plaza Riyadh Rdc Hotel & Convention, An...",Booking.com,930.00,930.00,2025-01-02,2025-01-03,331,4.5,NaN,24.738811,46.635284
6,23569851,Fairmont Ramla Serviced Residences,all.accor.com,1518.75,NaN,2025-01-02,2025-01-03,121,4.5,NaN,NaN,NaN
7,299190,"Holiday Inn Riyadh - Olaya, an IHG hotel",Booking.com,630.00,630.00,2025-01-02,2025-01-03,499,4.0,NaN,24.680237,46.690372
8,15239002,Shaza Riyadh,Booking.com,652.50,652.50,2025-01-02,2025-01-03,176,4.5,"['Free breakfast available', 'Free cancellatio...",24.675924,46.779200
9,1486058,"Crowne Plaza Riyadh Palace, an IHG hotel",MakeMyTrip,483.75,483.75,2025-01-02,2025-01-03,239,4.0,NaN,24.664728,46.711360

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1089 entries, 0 to 1088
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hotel_id    1089 non-null   int64
 1   hotel_name  1089 non-null   object
 2   SOURCE      1089 non-null   object
 3   price       1029 non-null   float64
 4   base_price  840 non-null    float64
 5   checkIn     1089 non-null   object
 6   checkOut    1089 non-null   object
 7   count       1089 non-null   int64
 8   rating      1089 non-null   float64
 9   Info        331 non-null    object
 10  latitude    651 non-null    float64
 11  longitude   651 non-null    float64
dtypes: float64(5), int64(2), object(5)
memory usage: 102.2+ KB

In [ ]:
df.describe()

,hotel_id,price,base_price,count,rating,latitude,longitude
count,1.089000e+03,1029.000000,840.000000,1089.000000,1089.000000,651.000000,651.000000
mean,1.094511e+07,1274.821429,867.334821,331.359045,4.232323,24.712797,46.691048
std,9.489783e+06,1189.632815,646.289942,405.379439,0.575002,0.043541,0.031306
min,2.991900e+05,71.250000,3.750000,1.000000,2.500000,24.641687,46.635284
25%,1.748545e+06,588.750000,502.500000,54.000000,4.000000,24.680944,46.675297
50%,8.470987e+06,813.750000,690.000000,214.000000,4.500000,24.704520,46.683575
75%,1.686598e+07,1605.000000,1091.250000,407.000000,4.500000,24.738811,46.718050
max,2.805409e+07,8617.500000,3701.250000,1626.000000,5.000000,24.808397,46.779200

In [ ]:
df.isnull().sum()

hotel_id        0
hotel_name      0
SOURCE          0
price          60
base_price    249
checkIn         0
checkOut        0
count           0
rating          0
Info          758
latitude      438
longitude     438
dtype: int64

In [ ]:
df.sort_values(by="price", ascending=False)[["hotel_name", "price", "rating"]].head(10)

                          hotel_name    price  rating
1015  Sheraton Riyadh Hotel & Towers  8617.50     4.0
1049  Sheraton Riyadh Hotel & Towers  8613.75     4.0
340   Sheraton Riyadh Hotel & Towers  8587.50     4.0
214          The Ritz-Carlton Riyadh  7413.75     4.5
445             The St. Regis Riyadh  7327.50     5.0
469             The St. Regis Riyadh  7327.50     5.0
544          The Ritz-Carlton Riyadh  6967.50     4.5
437          The Ritz-Carlton Riyadh  6630.00     4.5
1087         The Ritz-Carlton Riyadh  6570.00     4.5
576          The Ritz-Carlton Riyadh  6438.75     4.5

In [ ]:
df

,hotel_id,hotel_name,SOURCE,price,base_price,checkIn,checkOut,count,rating,Info,latitude,longitude
0,15215188,Fairmont Riyadh,all.accor.com,1605.00,NaN,2025-01-02,2025-01-03,220,4.5,NaN,24.808397,46.718050
1,9702375,Rosh Rayhaan by Rotana,Official Site,813.75,693.75,2025-01-02,2025-01-03,1311,4.5,"['Free breakfast available', 'Free cancellation']",24.700346,46.682137
2,15756839,Hilton Riyadh Hotel & Residences,Booking.com,1128.75,1128.75,2025-01-02,2025-01-03,1626,4.5,NaN,24.785522,46.727880
3,24143026,Joudyan Hotel,MakeMyTrip,588.75,472.50,2025-01-02,2025-01-03,317,5.0,"['Free breakfast available', 'Free cancellation']",24.713552,46.675297
4,969150,"Holiday Inn Riyadh - al Qasr, an IHG hotel",Booking.com,633.75,633.75,2025-01-02,2025-01-03,1073,4.5,NaN,24.683914,46.688030
...,...,...,...,...,...,...,...,...,...,...,...,...
1084,24001761,Warwick Riyadh,Agoda.com,483.75,NaN,2025-01-25,2025-01-29,5,2.5,NaN,NaN,NaN
1085,8470987,Al Oroba Hotel,Agoda.com,131.25,131.25,2025-01-25,2025-01-29,2,2.5,NaN,NaN,NaN
1086,7789088,"Crowne Plaza Riyadh Rdc Hotel & Convention, An...",Booking.com,3258.75,3258.75,2025-01-25,2025-01-29,331,4.5,NaN,24.738811,46.635284
1087,2366709,The Ritz-Carlton Riyadh,Booking.com,6570.00,3.75,2025-01-25,2025-01-29,1045,4.5,NaN,NaN,NaN
1088,16865982,Le Méridien Riyadh,LeMeridien.com,2895.00,NaN,2025-01-25,2025-01-29,78,4.5,"['Free breakfast available', 'Free cancellatio...",NaN,NaN

In [ ]:
df = df.dropna(subset=["price"])

In [ ]:
df['Info'] = df['Info'].fillna('No Info')

/tmp/ipykernel_335/183784032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Info'] = df['Info'].fillna('No Info')

In [ ]:
df.isnull().sum()

hotel_id        0
hotel_name      0
SOURCE          0
price           0
base_price    249
checkIn         0
checkOut        0
count           0
rating          0
Info            0
latitude      431
longitude     431
dtype: int64

In [ ]:
pd.to_datetime(df['checkIn'])

0      2025-01-02
1      2025-01-02
2      2025-01-02
3      2025-01-02
4      2025-01-02
          ...
1084   2025-01-25
1085   2025-01-25
1086   2025-01-25
1087   2025-01-25
1088   2025-01-25
Name: checkIn, Length: 1029, dtype: datetime64[ns]

In [ ]:
df['checkIn'] = pd.to_datetime(df['checkIn'])
df['checkOut'] = pd.to_datetime(df['checkOut'])

/tmp/ipykernel_335/2962800357.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['checkIn'] = pd.to_datetime(df['checkIn'])
/tmp/ipykernel_335/2962800357.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['checkOut'] = pd.to_datetime(df['checkOut'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1029 entries, 0 to 1088
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hotel_id    1029 non-null   int64
 1   hotel_name  1029 non-null   object
 2   SOURCE      1029 non-null   object
 3   price       1029 non-null   float64
 4   base_price  780 non-null    float64
 5   checkIn     1029 non-null   datetime64[ns]
 6   checkOut    1029 non-null   datetime64[ns]
 7   count       1029 non-null   int64
 8   rating      1029 non-null   float64
 9   Info        1029 non-null   object
 10  latitude    598 non-null    float64
 11  longitude   598 non-null    float64
dtypes: datetime64[ns](2), float64(5), int64(2), object(3)
memory usage: 104.5+ KB

In [ ]:
df['stay_days'] = (df['checkOut'] - df['checkIn']).dt.days
df

/tmp/ipykernel_335/2300411938.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['stay_days'] = (df['checkOut'] - df['checkIn']).dt.days

,hotel_id,hotel_name,SOURCE,price,base_price,checkIn,checkOut,count,rating,Info,latitude,longitude,stay_days
0,15215188,Fairmont Riyadh,all.accor.com,1605.00,NaN,2025-01-02,2025-01-03,220,4.5,No Info,24.808397,46.718050,1
1,9702375,Rosh Rayhaan by Rotana,Official Site,813.75,693.75,2025-01-02,2025-01-03,1311,4.5,"['Free breakfast available', 'Free cancellation']",24.700346,46.682137,1
2,15756839,Hilton Riyadh Hotel & Residences,Booking.com,1128.75,1128.75,2025-01-02,2025-01-03,1626,4.5,No Info,24.785522,46.727880,1
3,24143026,Joudyan Hotel,MakeMyTrip,588.75,472.50,2025-01-02,2025-01-03,317,5.0,"['Free breakfast available', 'Free cancellation']",24.713552,46.675297,1
4,969150,"Holiday Inn Riyadh - al Qasr, an IHG hotel",Booking.com,633.75,633.75,2025-01-02,2025-01-03,1073,4.5,No Info,24.683914,46.688030,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,24001761,Warwick Riyadh,Agoda.com,483.75,NaN,2025-01-25,2025-01-29,5,2.5,No Info,NaN,NaN,4
1085,8470987,Al Oroba Hotel,Agoda.com,131.25,131.25,2025-01-25,2025-01-29,2,2.5,No Info,NaN,NaN,4
1086,7789088,"Crowne Plaza Riyadh Rdc Hotel & Convention, An...",Booking.com,3258.75,3258.75,2025-01-25,2025-01-29,331,4.5,No Info,24.738811,46.635284,4
1087,2366709,The Ritz-Carlton Riyadh,Booking.com,6570.00,3.75,2025-01-25,2025-01-29,1045,4.5,No Info,NaN,NaN,4
1088,16865982,Le Méridien Riyadh,LeMeridien.com,2895.00,NaN,2025-01-25,2025-01-29,78,4.5,"['Free breakfast available', 'Free cancellatio...",NaN,NaN,4

In [ ]:
df['Free breakfast'] = df['Info'].str.contains('Free breakfast available', na=False)
df['Free cancellation'] = df['Info'].str.contains('Free cancellation', na=False)
df

/tmp/ipykernel_335/2415776074.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Free breakfast'] = df['Info'].str.contains('Free breakfast available', na=False)
/tmp/ipykernel_335/2415776074.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Free cancellation'] = df['Info'].str.contains('Free cancellation', na=False)

,hotel_id,hotel_name,SOURCE,price,base_price,checkIn,checkOut,count,rating,Info,latitude,longitude,stay_days,Free breakfast,Free cancellation
0,15215188,Fairmont Riyadh,all.accor.com,1605.00,NaN,2025-01-02,2025-01-03,220,4.5,No Info,24.808397,46.718050,1,False,False
1,9702375,Rosh Rayhaan by Rotana,Official Site,813.75,693.75,2025-01-02,2025-01-03,1311,4.5,"['Free breakfast available', 'Free cancellation']",24.700346,46.682137,1,True,True
2,15756839,Hilton Riyadh Hotel & Residences,Booking.com,1128.75,1128.75,2025-01-02,2025-01-03,1626,4.5,No Info,24.785522,46.727880,1,False,False
3,24143026,Joudyan Hotel,MakeMyTrip,588.75,472.50,2025-01-02,2025-01-03,317,5.0,"['Free breakfast available', 'Free cancellation']",24.713552,46.675297,1,True,True
4,969150,"Holiday Inn Riyadh - al Qasr, an IHG hotel",Booking.com,633.75,633.75,2025-01-02,2025-01-03,1073,4.5,No Info,24.683914,46.688030,1,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,24001761,Warwick Riyadh,Agoda.com,483.75,NaN,2025-01-25,2025-01-29,5,2.5,No Info,NaN,NaN,4,False,False
1085,8470987,Al Oroba Hotel,Agoda.com,131.25,131.25,2025-01-25,2025-01-29,2,2.5,No Info,NaN,NaN,4,False,False
1086,7789088,"Crowne Plaza Riyadh Rdc Hotel & Convention, An...",Booking.com,3258.75,3258.75,2025-01-25,2025-01-29,331,4.5,No Info,24.738811,46.635284,4,False,False
1087,2366709,The Ritz-Carlton Riyadh,Booking.com,6570.00,3.75,2025-01-25,2025-01-29,1045,4.5,No Info,NaN,NaN,4,False,False
1088,16865982,Le Méridien Riyadh,LeMeridien.com,2895.00,NaN,2025-01-25,2025-01-29,78,4.5,"['Free breakfast available', 'Free cancellatio...",NaN,NaN,4,True,True

In [ ]:
df = df.drop(columns=['Info'])
df

,hotel_id,hotel_name,SOURCE,price,base_price,checkIn,checkOut,count,rating,latitude,longitude,stay_days,Free breakfast,Free cancellation
0,15215188,Fairmont Riyadh,all.accor.com,1605.00,NaN,2025-01-02,2025-01-03,220,4.5,24.808397,46.718050,1,False,False
1,9702375,Rosh Rayhaan by Rotana,Official Site,813.75,693.75,2025-01-02,2025-01-03,1311,4.5,24.700346,46.682137,1,True,True
2,15756839,Hilton Riyadh Hotel & Residences,Booking.com,1128.75,1128.75,2025-01-02,2025-01-03,1626,4.5,24.785522,46.727880,1,False,False
3,24143026,Joudyan Hotel,MakeMyTrip,588.75,472.50,2025-01-02,2025-01-03,317,5.0,24.713552,46.675297,1,True,True
4,969150,"Holiday Inn Riyadh - al Qasr, an IHG hotel",Booking.com,633.75,633.75,2025-01-02,2025-01-03,1073,4.5,24.683914,46.688030,1,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,24001761,Warwick Riyadh,Agoda.com,483.75,NaN,2025-01-25,2025-01-29,5,2.5,NaN,NaN,4,False,False
1085,8470987,Al Oroba Hotel,Agoda.com,131.25,131.25,2025-01-25,2025-01-29,2,2.5,NaN,NaN,4,False,False
1086,7789088,"Crowne Plaza Riyadh Rdc Hotel & Convention, An...",Booking.com,3258.75,3258.75,2025-01-25,2025-01-29,331,4.5,24.738811,46.635284,4,False,False
1087,2366709,The Ritz-Carlton Riyadh,Booking.com,6570.00,3.75,2025-01-25,2025-01-29,1045,4.5,NaN,NaN,4,False,False
1088,16865982,Le Méridien Riyadh,LeMeridien.com,2895.00,NaN,2025-01-25,2025-01-29,78,4.5,NaN,NaN,4,True,True

In [ ]:
df[['price', 'base_price']].isnull().sum()

price           0
base_price    249
dtype: int64

In [ ]:
df[['price', 'base_price']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1029 entries, 0 to 1088
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price       1029 non-null   float64
 1   base_price  780 non-null    float64
dtypes: float64(2)
memory usage: 24.1 KB

In [ ]:
df[['price', 'base_price']].describe().T

,count,mean,std,min,25%,50%,75%,max
price,1029.0,1274.821429,1189.632815,71.25,588.75,813.75,1605.0000,8617.50
base_price,780.0,863.826923,649.596150,3.75,502.50,686.25,1088.4375,3701.25

In [ ]:
df['discount'] = df['price'] - df['base_price']
df['discount_percent'] = ((df['price'] - df['base_price']) / df['base_price']) * 100

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df

,hotel_id,hotel_name,SOURCE,price,base_price,checkIn,checkOut,count,rating,latitude,longitude,stay_days,Free breakfast,Free cancellation,discount,discount_percent
0,15215188,Fairmont Riyadh,all.accor.com,1605.00,NaN,2025-01-02,2025-01-03,220,4.5,24.808397,46.718050,1,False,False,NaN,NaN
1,9702375,Rosh Rayhaan by Rotana,Official Site,813.75,693.75,2025-01-02,2025-01-03,1311,4.5,24.700346,46.682137,1,True,True,120.00,17.297297
2,15756839,Hilton Riyadh Hotel & Residences,Booking.com,1128.75,1128.75,2025-01-02,2025-01-03,1626,4.5,24.785522,46.727880,1,False,False,0.00,0.000000
3,24143026,Joudyan Hotel,MakeMyTrip,588.75,472.50,2025-01-02,2025-01-03,317,5.0,24.713552,46.675297,1,True,True,116.25,24.603175
4,969150,"Holiday Inn Riyadh - al Qasr, an IHG hotel",Booking.com,633.75,633.75,2025-01-02,2025-01-03,1073,4.5,24.683914,46.688030,1,False,False,0.00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1084,24001761,Warwick Riyadh,Agoda.com,483.75,NaN,2025-01-25,2025-01-29,5,2.5,NaN,NaN,4,False,False,NaN,NaN
1085,8470987,Al Oroba Hotel,Agoda.com,131.25,131.25,2025-01-25,2025-01-29,2,2.5,NaN,NaN,4,False,False,0.00,0.000000
1086,7789088,"Crowne Plaza Riyadh Rdc Hotel & Convention, An...",Booking.com,3258.75,3258.75,2025-01-25,2025-01-29,331,4.5,24.738811,46.635284,4,False,False,0.00,0.000000
1087,2366709,The Ritz-Carlton Riyadh,Booking.com,6570.00,3.75,2025-01-25,2025-01-29,1045,4.5,NaN,NaN,4,False,False,6566.25,175100.000000
1088,16865982,Le Méridien Riyadh,LeMeridien.com,2895.00,NaN,2025-01-25,2025-01-29,78,4.5,NaN,NaN,4,True,True,NaN,NaN

In [ ]:
df[["hotel_name",'price']].max()

hotel_name    ibis Riyadh Olaya Street
price                           8617.5
dtype: object

In [ ]:
df[["hotel_name",'rating']].max()

hotel_name    ibis Riyadh Olaya Street
rating                             5.0
dtype: object

In [ ]:
df.groupby('SOURCE')['price'].mean()

SOURCE
Agoda.com           532.500000
Booking.com        1132.149758
Expedia             266.250000
Fairmont           2249.250000
Hotels.com          577.500000
Hyatt.com          1775.625000
JW Marriott        2325.441176
LeMeridien.com     2449.500000
MakeMyTrip          596.484375
Marriott           1494.886364
Marriott Hotels    1691.100000
Official Site      1247.884615
Prestigia.com      1297.031250
Sheraton.com       1762.800000
StRegis.com        3658.806818
Trip.com           8613.750000
Vio.com            1363.593750
all.accor.com      2425.650000
Name: price, dtype: float64

In [ ]:
df[df['Free breakfast']]['hotel_name']

1               Rosh Rayhaan by Rotana
3                        Joudyan Hotel
8                         Shaza Riyadh
15              Carawan Al Fahad Hotel
17             Continent Al Waha Hotel
                     ...
1073                Le Méridien Riyadh
1074    Sheraton Riyadh Hotel & Towers
1076                   Fairmont Riyadh
1081           OYO 146 Al Asemah Hotel
1088                Le Méridien Riyadh
Name: hotel_name, Length: 327, dtype: object

In [ ]:
df[df['Free cancellation']]['hotel_name']

1               Rosh Rayhaan by Rotana
3                        Joudyan Hotel
8                         Shaza Riyadh
15              Carawan Al Fahad Hotel
17             Continent Al Waha Hotel
                     ...
1073                Le Méridien Riyadh
1074    Sheraton Riyadh Hotel & Towers
1076                   Fairmont Riyadh
1081           OYO 146 Al Asemah Hotel
1088                Le Méridien Riyadh
Name: hotel_name, Length: 318, dtype: object

In [ ]:
df.to_csv('cleaned_riyadh_hotels.csv', index=False)
from google.colab import files
files.download('cleaned_riyadh_hotels.csv')